"""Update field name

Revision ID: 077e1b37396b
Revises: 40a9d1764c17
Create Date: 2023-12-23 21:12:53.400648

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = "077e1b37396b"
down_revision: Union[str, None] = "40a9d1764c17"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "studycategory",
        sa.Column(
            "is_active",
            sa.Boolean(),
            nullable=False,
            server_default=sa.sql.expression.false(),
        ),
    )
    op.execute("UPDATE studycategory SET is_active = selected")
    op.drop_column("studycategory", "selected")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "studycategory",
        sa.Column(
            "selected",
            sa.BOOLEAN(),
            autoincrement=False,
            nullable=False,
            server_default=sa.sql.expression.false(),
        ),
    )
    op.execute("UPDATE studycategory SET selected = is_active")

    op.drop_column("studycategory", "is_active")
    # ### end Alembic commands ###
