"""Update User Model AWS KEY

Revision ID: 481f9950392a
Revises: 27d16b11dc2c
Create Date: 2024-07-12 17:40:06.933265

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '481f9950392a'
down_revision: Union[str, None] = '27d16b11dc2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('profile_photo_key', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_column('user', 'profile_photo_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('profile_photo_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('user', 'profile_photo_key')
    # ### end Alembic commands ###
