"""Remove unique constraint is_active daily goal

Revision ID: 7a69adf84246
Revises: 277ce49462e1
Create Date: 2024-07-13 00:09:26.883334

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '7a69adf84246'
down_revision: Union[str, None] = '277ce49462e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_active_goal', 'dailygoal', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_user_active_goal', 'dailygoal', ['user_id', 'is_active'])
    # ### end Alembic commands ###
