"""Add time settings

Revision ID: 93cf3345cfac
Revises: e04f15e7538c
Create Date: 2024-07-19 20:53:03.279201

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '93cf3345cfac'
down_revision: Union[str, None] = 'e04f15e7538c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('timesettings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_countdown', sa.Boolean(), nullable=False),
    sa.Column('is_selected', sa.Boolean(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('short_break_duration', sa.Integer(), nullable=False),
    sa.Column('long_break_duration', sa.Integer(), nullable=False),
    sa.Column('long_break_interval', sa.Integer(), nullable=False),
    sa.Column('is_sound', sa.Boolean(), nullable=False),
    sa.Column('sound_interval', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('timesettings')
    # ### end Alembic commands ###
