"""Update time settings

Revision ID: 98b5ab87099b
Revises: 93cf3345cfac
Create Date: 2024-07-20 02:35:44.395513

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = "98b5ab87099b"
down_revision: Union[str, None] = "93cf3345cfac"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "timesettings", "duration", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "timesettings",
        "short_break_duration",
        existing_type=sa.INTEGER(),
        nullable=True,
    )
    op.alter_column(
        "timesettings", "long_break_duration", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "timesettings", "long_break_interval", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "timesettings", "is_sound", existing_type=sa.BOOLEAN(), nullable=True
    )
    op.alter_column(
        "timesettings", "sound_interval", existing_type=sa.INTEGER(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "timesettings", "sound_interval", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "timesettings", "is_sound", existing_type=sa.BOOLEAN(), nullable=False
    )
    op.alter_column(
        "timesettings",
        "long_break_interval",
        existing_type=sa.INTEGER(),
        nullable=False,
    )
    op.alter_column(
        "timesettings",
        "long_break_duration",
        existing_type=sa.INTEGER(),
        nullable=False,
    )
    op.alter_column(
        "timesettings",
        "short_break_duration",
        existing_type=sa.INTEGER(),
        nullable=False,
    )
    op.alter_column(
        "timesettings", "duration", existing_type=sa.INTEGER(), nullable=False
    )
    # ### end Alembic commands ###
