"""Initial migration

Revision ID: c73c26aaa64d
Revises: 
Create Date: 2023-12-03 00:51:26.409275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'c73c26aaa64d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('studycategory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_studycategory_title'), 'studycategory', ['title'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('bio', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=False)
    op.create_table('dailygoal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('block_size', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dailygoal_user_id'), 'dailygoal', ['user_id'], unique=False)
    op.create_table('usercategorylink',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('study_category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['study_category_id'], ['studycategory.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'study_category_id')
    )
    op.create_table('studyblock',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start', sa.DateTime(), nullable=False),
    sa.Column('end', sa.DateTime(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('daily_goal_id', sa.Integer(), nullable=False),
    sa.Column('study_category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['daily_goal_id'], ['dailygoal.id'], ),
    sa.ForeignKeyConstraint(['study_category_id'], ['studycategory.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_studyblock_daily_goal_id'), 'studyblock', ['daily_goal_id'], unique=False)
    op.create_index(op.f('ix_studyblock_study_category_id'), 'studyblock', ['study_category_id'], unique=False)
    op.create_index(op.f('ix_studyblock_user_id'), 'studyblock', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_studyblock_user_id'), table_name='studyblock')
    op.drop_index(op.f('ix_studyblock_study_category_id'), table_name='studyblock')
    op.drop_index(op.f('ix_studyblock_daily_goal_id'), table_name='studyblock')
    op.drop_table('studyblock')
    op.drop_table('usercategorylink')
    op.drop_index(op.f('ix_dailygoal_user_id'), table_name='dailygoal')
    op.drop_table('dailygoal')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_studycategory_title'), table_name='studycategory')
    op.drop_table('studycategory')
    # ### end Alembic commands ###
